"""API request/response models."""

from schemas.api_models.types import DevicePointData, ModbusRegisterValues, PollResult
from schemas.api_models.requests import (
    ReadRequest,
    DeviceCreateRequest,
    DeviceUpdate,
    SiteCreateRequest,
    SiteUpdateRequest,
    ConfigCreateRequest,
    ConfigUpdate,
    PollingConfig,
    Coordinates,
    Location,
    ConfigPoint,
)
from schemas.api_models.mappers import RegisterData, RegisterValue
from schemas.api_models.responses import (
    ReadResponse,
    SimpleReadResponse,
    HealthResponse,
    DeviceListItem,
    DeviceResponse,
    DeviceDeleteResponse,
    DevicePoints,
    DevicePointsCategoryGrouped,
    DeviceWithConfigs,
    DeviceWithPoints,
    SiteResponse,
    SiteDeleteResponse,
    SiteComprehensiveResponse,
    SiteComprehensiveWithConfigsResponse,
    ConfigResponse,
    ConfigDeleteResponse,
    DevicePointResponse,
    TimeseriesPoint,
    PointTimeseries,
    PointLatest,
    TimeseriesMeta,
    LatestMeta,
    TimeseriesResponse,
    LatestResponse,
)

__all__ = [
    "DevicePointData",
    "ModbusRegisterValues",
    "PollResult",
    "ReadRequest",
    "ReadResponse",
    "RegisterData",
    "RegisterValue",
    "SimpleReadResponse",
    "HealthResponse",
    "DeviceCreateRequest",
    "DeviceUpdate",
    "SiteCreateRequest",
    "SiteUpdateRequest",
    "ConfigCreateRequest",
    "ConfigUpdate",
    "PollingConfig",
    "DeviceListItem",
    "DeviceResponse",
    "DeviceDeleteResponse",
    "DevicePoints",
    "DevicePointsCategoryGrouped",
    "DeviceWithConfigs",
    "DeviceWithPoints",
    "SiteResponse",
    "SiteDeleteResponse",
    "SiteComprehensiveResponse",
    "SiteComprehensiveWithConfigsResponse",
    "ConfigResponse",
    "ConfigDeleteResponse",
    "DevicePointResponse",
    "Coordinates",
    "Location",
    "ConfigPoint",
]
