apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pae-backend-ot-prod
  namespace: argocd
  # Keep the app from being pruned if the Application manifest is removed by mistake.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yazdanimehrdad1/pae-backend-ot.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: pae-backend-ot-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
