apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pae-rtac-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pae-rtac-server
  # min/max are overridden per overlay.
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
