apiVersion: v1
kind: Service
metadata:
  name: pae-rtac-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pae-rtac-server
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
