apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rtac-modbus-dev

resources:
- namespace.yaml
- ../../base

images:
- name: pae-rtac-server
  newName: us-central1-docker.pkg.dev/prd-pae-rtac-server/pae/pae-rtac-server
  newTag: de48b2e02bbdb3e49a4d2667d73f65e1db7aaf27

replicas:
- count: 1
  name: pae-rtac-server

configMapGenerator:
- behavior: merge
  literals:
  - LOG_LEVEL=DEBUG
  - AGGREGATOR_MODBUS_HOST=REPLACE_AGGREGATOR_DEV_HOST
  name: pae-rtac-server-config

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: pae-rtac-server
    spec:
      template:
        spec:
          initContainers:
            - name: cloud-sql-proxy
              env:
                - name: INSTANCE_CONNECTION_NAME
                  value: REPLACE_PROJECT:REGION:rtac-pg-dev
          containers:
            - name: app
              resources:
                requests:
                  cpu: 100m
                  memory: 256Mi
                limits:
                  memory: 512Mi
  target:
    kind: Deployment
    name: pae-rtac-server
- patch: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: pae-rtac-server-migrate
    spec:
      template:
        spec:
          initContainers:
            - name: cloud-sql-proxy
              env:
                - name: INSTANCE_CONNECTION_NAME
                  value: REPLACE_PROJECT:REGION:rtac-pg-dev
  target:
    kind: Job
    name: pae-rtac-server-migrate
- patch: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: pae-rtac-server
      annotations:
        iam.gke.io/gcp-service-account: rtac-modbus-dev@REPLACE_PROJECT.iam.gserviceaccount.com
  target:
    kind: ServiceAccount
    name: pae-rtac-server
- patch: |-
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: pae-rtac-server
    spec:
      minReplicas: 1
      maxReplicas: 2
  target:
    kind: HorizontalPodAutoscaler
    name: pae-rtac-server
